### ISSUE TITLE
go get github.com/fabdem/go-crowdinv2 fails with error

### ISSUE THREAD

**Issue by meetmatt** [fabdem/go-crowdinv2#1]
Dear maintainers,

First of all, thank you for this repo!
I'm trying to build a CLI tool that uses your package as dependency, but I ran into an issue.

Steps to reproduce:
1. mkdir test && cd test
2. go mod init github.com/meetmatt/translation
3. go get github.com/fabdem/go-crowdinv2

Expected:
go.mod file updated, go.sum file created, go-crowdinv2 module downloaded and cached.

Actual:
go: github.com/fabdem/go-crowdinv2@v1.0.2-0.20220503210627-8c7c7f59c36f: parsing go.mod:
        module declares its path as: crowdin
                but was required as: github.com/fabdem/go-crowdinv2

I think the fix should be trivial to solve by updating the go.mod file, replacing the module name with full repo path.

**Comment by meetmatt** [comment]
Please review the proposed fix:
https://github.com/fabdem/go-crowdinv2/pull/2

**Comment by fabdem** [comment]
Thank you!
